import {Platform} from 'react-native';

export const Icons = {
  Splash: require('../assets/icons/Splash.png'),
  logoCircle: require('../assets/icons/logoCircle.png'),
  RightArrow: require('../assets/icons/RightArrow.png'),
  Cancel: require('../assets/icons/Cancel.png'),
  BigFlag: require('../assets/icons/BigFlag.png'),
  Flag: require('../assets/icons/flag.png'),
  Search: require('../assets/icons/search.png'),
  Delete: require('../assets/icons/delete.png'),
  Plus: require('../assets/icons/Plus.png'),
  LeftArrow: require('../assets/icons/LeftArrow.png'),
  Write: require('../assets/icons/Write.png'),
  Location: require('../assets/icons/location.png'),
  logo: require('../assets/icons/logo.png'),
  gallery: require('../assets/icons/Gallery.png'),
  downarrow: require('../assets/icons/downarrow.png'),
  connectbottom: require('../assets/icons/connectbottom.png'),
  connecttop: require('../assets/icons/connecttop.png'),
  selectgps: require('../assets/icons/selectgps.png'),
  firmwareupdate: require('../assets/icons/firmwareupdate.png'),
  //Image
  welcomepagesideimg: require('../assets/images/welcomepagesideimg.png'),
  pairing: require('../assets/images/pairing.png'),
  pairingprogress: require('../assets/images/pairingprogress.png'),
  Exclamatory: require('../assets/icons/Exclamatory.png'),
  back: require('../assets/icons/back.png'),
  calendar: require('../assets/icons/calendar.png'),
  clock: require('../assets/icons/clock.png'),
  flag: require('../assets/icons/flag.png'),
  delete1: require('../assets/icons/delete1.png'),
  battery: require('../assets/icons/battery.png'),
  arc: require('../assets/icons/arc.png'),
  headPhone: require('../assets/icons/headPhone.png'),
  headphoneNew: require('../assets/icons/headphone_new.png'),
  board: require('../assets/icons/board.png'),
  Connect: require('../assets/icons/connectproduct.png'),
  Report: require('../assets/icons/reportmapping.png'),
  Privacy: require('../assets/icons/privacy.png'),
  Product: require('../assets/icons/productsupport.png'),
  Update: require('../assets/icons/update.png'),
  Warranty: require('../assets/icons/warranty.png'),
  // back: require('../assets/icons/back.png'),
  front: require('../assets/icons/front.png'),
  // search: require('../assets/icons/search.png'),
  // flag: require('../assets/icons/flag.png'),
  toggle: require('../assets/icons/toggle.png'),
  uncheck: require('../assets/icons/uncheck.png'),
  technical: require('../assets/icons/technical.png'),
  faq: require('../assets/icons/faq.png'),
  powakaddy: require('../assets/icons/powakaddy.png'),
  usermanual: require('../assets/icons/usermanual.png'),
  phone: require('../assets/icons/phone.png'),
  calender: require('../assets/icons/calender.png'),
  // location: require('../assets/icons/location.png'),
  mail: require('../assets/icons/mail.png'),
  tick: require('../assets/icons/tick.png'),
  yellowCirclelogo: require('../assets/icons/yellowCirclelogo.png'),
  query: require('../assets/icons/query.png'),
  batterygrey: require('../assets/icons/batterygrey.png'),
  location1: require('../assets/icons/location1.png'),
  circlelogo: require('../assets/icons/circlelogo.png'),
  spin: require('../assets/images/spin.png'),
  spinLogo: require('../assets/images/spinLogo.png'),
  uncheck: require('../assets/icons/uncheck.png'),
  check: require('../assets/icons/checkbox.png'),
  spinLogo: require('../assets/images/spinLogo.png'),
  GreenNone:require('../assets/icons/GreenNone.png'),
  MaxCourse:require('../assets/icons/MaxCourse.png'),
  SendMail:require('../assets/icons/SendMail.png'),
  Show : require('../assets/icons/Show.png'),
  hide : require('../assets/icons/hide.png'),
  UserLogo: require('../assets/icons/UserLogo.png'),
  LinkIcon : require('../assets/icons/LinkIcon.png'),
  UserAccount : require('../assets/icons/UserAccount.png')
};
// logo.png
export const Colors = {
  white: '#FFFFFF',
  lightblack: Platform.OS == 'ios' ? '#111111' : '#242424',
  // black: '#010402',
  yellow: '#FFC211',
  grey: '#C4C4C4',
  black: '#000000',
  bgColor: '#010402',
  primary: '#FFC211',
  black3: '#151515',
  black2: '#222323',
  green: '#3DAE48',
  grey: '#DCDCDC',
  darkGrey: '#484848',
  red: '#D2232B',
  line: '#151515',
  greyDark: '#151515',
  semiDark: '#4B4B4B',
  greyMedium: '#111111',
  darkStroke: '#272833',
  lightGrey: '#C4C4C4',
  background: '#111111',
  semiDark: '#4B4B4B',
  border: '#272833',
  textColor: '#929292',
};

export const Fonts = {
  RobotoBold: 'Roboto-Bold',
  RobotoLight: 'Roboto-Light',
  RobotoMedium: 'Roboto-Medium',
  RobotoRegular: 'Roboto-Regular',
};
